### ISSUE TITLE
in `pbkdf2_hmac_sha1': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by msabramo** [dlokesh/1pass#3]
```
$ 1pass --key mail.google.com
Enter your master password:  ********

/usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/decrypt.rb:26:in `pbkdf2_hmac_sha1': no implicit conversion from nil to integer (TypeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/decrypt.rb:26:in `derive_pbkdf2'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/decrypt.rb:45:in `decrypt_pbkdf2'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/encryption_key.rb:27:in `unlock'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/encryption_key.rb:11:in `block in unlock'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/encryption_key.rb:11:in `collect'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/encryption_key.rb:11:in `unlock'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/keychain.rb:16:in `unlock'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/1pass.rb:18:in `load'
	from /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/bin/1pass:34:in `<top (required)>'
	from /usr/local/bin/1pass:23:in `load'
	from /usr/local/bin/1pass:23:in `<main>'
```

This is because `iterations` is nil in this function as shown below:

```
$ 1pass --key mail.google.com
Enter your master password:  ********

From: /usr/local/lib/ruby/gems/2.3.0/gems/1pass-0.1.2/lib/decrypt.rb @ line 26 Decrypt.derive_pbkdf2:

    24: 	def self.derive_pbkdf2(password, salt, iterations)
    25:               require 'pry'; binding.pry
 => 26: 		key_and_iv = OpenSSL::PKCS5.pbkdf2_hmac_sha1(password, salt, iterations, 32)
    27: 		{key: key_and_iv[0,16], iv: key_and_iv[16..-1]}
    28: 	end

[1] pry(Decrypt)> iterations
=> nil
[2] pry(Decrypt)> c
```

I have 1Password 6.3.1 on a Mac.

```
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
```

**Comment by msabramo** [comment]
So my Dropbox 1Password file (the one I use) is using 10,000 iterations, but the 1pass gem is defaulting to using `/Users/marca/Library/Application Support/1Password/1Password.agilekeychain` and that file doesn't have `iterations` in it.

```
$ cat ~/Library/Application\ Support/1Password/1Password.agilekeychain/data/default/encryptionKeys.js | jq '.list[] | {level: .level, iterations: .iterations}'
{
  "level": "SL3",
  "iterations": null
}
{
  "level": "SL5",
  "iterations": null
}
```

Maybe this could just use a better error message?

**Comment by msabramo** [comment]
I was able to get things working by doing:

```
pushd ~/Library/Application\ Support/1Password
ln -s ~/Dropbox/Library/Application\ Support/1Password/1Password.agilekeychain .
```

Unfortunately, the `1pass` command line program doesn't allow specifying the path to the agilekeychain file.
